<?php

namespace PDS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagesRepository extends EntityRepository
{
    private $message = array();
    
    public function getMessagesReceivedJoinUsers($con, $idUser, $limit = 10, $offset = 0, $orderBy = 'date', $ordering = 'desc')
    {
        if(empty($this->messages['receivedWithUser'])){
            $query = $con->query(
                sprintf("
                        SELECT *, m.date as date_message, m.id as message_id
                        FROM Messages m
                        INNER JOIN Users u ON u.id = m.from_user
                        WHERE m.is_read = false
                        AND m.to_user = %d
                        ORDER BY %s %s
                        %s %s
                    ",
                    (integer) $idUser,
                    $orderBy,
                    $ordering,
                    empty($limit) ? '' : 'LIMIT '.$limit,
                    empty($offset) ? '' : 'OFFSET '.$offset
                )
            );
            $this->messages['receivedWithUser'] = $query->fetchAll(\PDO::FETCH_ASSOC);
        }
        return $this->messages['receivedWithUser'];
    }
    
    public function getMessagesJoinUsers($con, $idUser, $limit = 10, $offset = 0, $orderBy = 'date', $ordering = 'desc')
    {
        if(empty($this->messages['allWithUser'])){
            $query = $con->query(
                sprintf("
                        SELECT *, m.date as date_message, m.id as message_id
                        FROM Messages m
                        INNER JOIN Users u ON u.id = m.from_user
                        WHERE m.to_user = %d
                        ORDER BY %s %s
                        %s %s
                    ",
                    (integer) $idUser,
                    $orderBy,
                    $ordering,
                    empty($limit) ? '' : 'LIMIT '.$limit,
                    empty($offset) ? '' : 'OFFSET '.$offset
                )
            );
            $this->messages['allWithUser'] = $query->fetchAll(\PDO::FETCH_ASSOC);
        }
        return $this->messages['allWithUser'];
    }
    
    public function getAllMessagesJoinUsers($con, $idUser, $limit = 10, $offset = 0, $orderBy = 'date', $ordering = 'desc')
    {
        if(empty($this->messages['allWithUser'])){
            $query = $con->query(
                sprintf("
                        SELECT
                            m.id as m_id,
                            m.from_user as m_from_user,
                            m.to_user as m_to_user,
                            m.message as m_message,
                            m.is_read as m_is_read,
                            m.date as m_date,
                            u.id as from_id,
                            u.username as from_username,
                            u.username_canonical as from_username_canonical,
                            u.email as from_email,
                            u.email_canonical as from_email_canonical,
                            u.avatar as from_avatar,
                            u2.id as to_id,
                            u2.username as to_username,
                            u2.username_canonical as to_username_canonical,
                            u2.email as to_email,
                            u2.email_canonical as to_email_canonical,
                            u2.avatar as to_avatar
                        FROM Messages m
                        INNER JOIN Users u ON u.id = m.from_user
                        INNER JOIN Users u2 ON u2.id = m.to_user
                        WHERE m.to_user = %d
                        OR m.from_user = %d
                        ORDER BY %s %s
                        %s %s
                    ",
                    (integer) $idUser,
                    (integer) $idUser,
                    $orderBy,
                    $ordering,
                    empty($limit) ? '' : 'LIMIT '.$limit,
                    empty($offset) ? '' : 'OFFSET '.$offset
                )
            );
            $this->messages['allWithUser'] = $query->fetchAll(\PDO::FETCH_ASSOC);
        }
        return $this->messages['allWithUser'];
    }
    
    public function getMessagesReveivedNotReadCount($con, $idUser)
    {
        $qb = $this->createQueryBuilder('m');
        $qb->select('COUNT(m)')
           ->where('m.toUser = :id')
           ->andWhere('m.isRead = false')
           ->setParameter('id', $idUser);
        
        return $qb->getQuery()->getSingleScalarResult();
    }
    
    public function getAllMessagesCount($con, $idUser)
    {
        $qb = $this->createQueryBuilder('m');
        $qb->select('COUNT(m)')
           ->where('m.toUser = :id')
             ->setParameter('id', $idUser)
           ->orWhere('m.fromUser = :id')
             ->setParameter('id', $idUser);
        
        return $qb->getQuery()->getSingleScalarResult();
    }
}
