<?php

namespace PDS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RelationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationsRepository extends EntityRepository
{
}
